{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "cyberchef.fullname" . }}
  labels:
    {{- include "cyberchef.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "cyberchef.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
