name: Release

on:
  push:
    branches:
      - master
  schedule:
     - cron: "0 0 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CHART_DIR: charts/cyberchef
  CHART_REPOSITORY: ghcr.io/${{ github.repository_owner }}/charts

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    if: contains(github.event.head_commit.message, 'Update dependency gchq/CyberChef') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from Dockerfile
        if: github.event_name != 'schedule'
        run: |
          sed -nE 's/ARG CYBERCHEF_VERSION="(.*)"/TAG=\1/p' Dockerfile >> $GITHUB_ENV

      - name: Tag nightly
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          echo "TAG=nightly" >> $GITHUB_ENV
        
      - name: Get latest commit hash
        if: env.TAG == 'nightly'
        run: |
          COMMIT=$(curl -s https://api.github.com/repos/gchq/CyberChef/commits/master | jq -r .sha)
          echo "BUILD_COMMIT=${COMMIT:0:7}" >> $GITHUB_ENV
      
      - name: Check if nightly build exists
        if: env.TAG == 'nightly'
        id: check_nightly
        run: |
          if docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nightly:${{ env.BUILD_COMMIT }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},enable=${{ env.TAG != 'nightly' }}
            name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nightly,enable=${{ env.TAG == 'nightly' }}
          tags: |
            type=semver,pattern={{raw}},value=${{ env.TAG }},enable=${{ env.TAG != 'nightly' }}
            type=schedule,pattern=nightly,enable=${{ github.event_name == 'schedule' }}
            type=schedule,pattern={{date 'YYYYMMDD'}},enable=${{ github.event_name == 'schedule' }}
            type=raw,value={{date 'YYYYMMDD'}},enable=${{ github.event_name == 'workflow_dispatch' }}
            type=raw,value=nightly,enable=${{ github.event_name == 'workflow_dispatch' }}
            type=raw,value=${{ env.BUILD_COMMIT }},enable=${{ env.TAG == 'nightly' }}

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        uses: docker/build-push-action@v6
        if: steps.check_nightly.outputs.exists != 'true' || env.TAG != 'nightly'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_TYPE=${{ env.TAG == 'nightly' && 'git' || 'release' }}
            CYBERCHEF_VERSION=${{ env.TAG == 'nightly' && 'master' || env.TAG }}
            BUILD_COMMIT=${{ env.BUILD_COMMIT || '' }}

  release-chart:
    needs: build-and-push
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to registry
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | \
            helm registry login \
              -u '${{ github.actor }}' \
              --password-stdin \
              ghcr.io

      - name: Package chart
        run: |
          echo PACKAGE=$(helm package ${{ env.CHART_DIR }} -u | cut -d " " -f 8) >> ${GITHUB_ENV}

      - name: Push chart
        run: |
          helm push \
            ${{ env.PACKAGE }} \
            oci://${{ env.CHART_REPOSITORY }}
